### PR TITLE
Updates SSL version

### PR DESCRIPTION
**Pull request by mjvk**
This version conflicts with Qt for example. It is possible to downgrade the Qt version, but as this one is quite old, I think it is better to upgrade the cmake one.

### CODE REVIEW

**Comment by Adnn** [comment]
Hi. This merge actually broke our build pipeline, where downstream directly requires OpenSLL.

See: https://github.com/conan-io/conan/issues/5651#issue-482848435

**Comment by uilianries** [comment]
Hi @mjvk ! I goona a new PR with OpenSSL as private requirement. Your will solve only your problem, but it cause a new problem to anyone who uses cmake_installer + OpenSSL 1.0

**Comment by mjvk** [comment]
Ok sounds good! Still might be good to upgrade SSL, typically one of those packages you'd rather not keep old versions of :-).

**Comment by uilianries** [comment]
Good point! lemme fix this bug first, I'll open a new PR with OpenSSL 1.1.1c.

Best regards!

**Pull request closed without merging**
